variables:
  GIT_SSL_NO_VERIFY: "1"
.check: &check
    - VERSION_FROM_PACKAGE=$(node -p -e "require('./package.json').version")
    - echo $VERSION
    - echo $VERSION_FROM_PACKAGE
    - if [ $VERSION == $VERSION_FROM_PACKAGE ]; then
        echo "Version match";
      else
        echo "The version doesnt match the package.json and the TAG" &&
        exit -1;
      fi
.addCredential: &addCredential
    - rm -f ~/.npmrc
    - npm config set registry=$NPM_DOMAIN_NAME
    - npm config set _auth="$(echo -n $XRHTSERVICE_USER:$XRHTSERVICE_PASS | base64)"
    - npm whoami

.package: &package
    - npm config set strict-ssl false
    - npm --userconfig ~/.npmrc publish --registry $NPM_DOMAIN_NAME

.packageSamples: &packageSamples
    - cd Samples~/
    - npm config set strict-ssl false
    - npm publish --registry $NPM_DOMAIN_NAME

stages:
  - check
  - addCredential
  - package
  - packageSamples

check:
  stage: check
  tags:
    - HaT_SDK
  except:
    - branches
  before_script:
    # additional variables
    - VERSION=$(echo $CI_COMMIT_REF_NAME)
  script:
    *check
addCredential:
  stage: addCredential
  except:
    - branches
  tags:
    - HaT_SDK
  script:
    *addCredential

package:
  stage: package
  except:
    - branches
  environment:
    name: preview
  tags:
    - HaT_SDK
  script:
    *package

packageSamples:
  stage: packageSamples
  except:
    - branches
  environment:
    name: preview
  tags:
    - HaT_SDK
  script:
    *packageSamples
